"""add is_active to students

Revision ID: 1147dd1d5074
Revises: efd77d508819
Create Date: 2026-06-28 10:56:23.264160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1147dd1d5074'
down_revision: Union[str, Sequence[str], None] = 'efd77d508819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "students",
    sa.Column(
        "is_active",
        sa.Boolean(),
        nullable=False,
        server_default=sa.text("true")
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
